version: '3.8'

services:
  gridflow-gui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gridflow-dashboard
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
